//! Differential format detection test against the baseline corpus.
//!
//! This test reads each sample from the `corpus/` directory (generated by
//! `tools/corpus/generate_baseline_corpus.py`), runs the full ProbeTable
//! against it, and verifies that the strongest candidate matches the
//! expected format.
//!
//! The corpus is project-generated (no third-party bytes) and covers all
//! formats implemented in Phase 2. See `docs/design/testing.md` section 12
//! and `corpus/manifest.json`.

#![forbid(unsafe_code)]

use diec_core::format::FormatStrength;
use diec_core::input::{ByteRange, ByteSource, ByteView, MemorySource};
use diec_formats::ProbeTable;
use std::path::PathBuf;

/// Corpus sample: (filename, expected strongest probe name).
///
/// Formats not yet probed (empty, text, BMP, WAV, PYC) are excluded.
/// APK/JAR/IPA are ZIP-based, so the probe detects ZIP.
const CORPUS_EXPECTATIONS: &[(&str, &str)] = &[
    ("minimal.elf", "ELF64"),
    ("minimal-elf32.elf", "ELF32"),
    ("minimal.exe", "PE32"),
    ("minimal-pe64.exe", "PE64"),
    ("minimal.macho", "Mach-O 64"),
    ("minimal-macho32.macho", "Mach-O 32"),
    ("minimal-fat.macho", "Mach-O FAT"),
    ("minimal.dex", "DEX"),
    ("Minimal.class", "Java Class"),
    ("minimal.pyc", "PYC"),
    ("pixel.png", "PNG"),
    ("pixel.jpg", "JPEG"),
    ("pixel.bmp", "BMP"),
    ("tone.wav", "WAV"),
    ("minimal.pdf", "PDF"),
    ("minimal.cfbf", "CFBF"),
    ("payload.zip", "ZIP"),
    ("minimal.apk", "ZIP"),
    ("minimal.jar", "ZIP"),
    ("minimal.ipa", "ZIP"),
    ("minimal.rar", "RAR"),
    ("minimal.iso", "ISO9660"),
    ("payload.tar", "TAR"),
    ("payload.txt.gz", "GZIP"),
];

/// Samples that should produce no candidates (non-binary or empty).
const CORPUS_NO_MATCH: &[&str] = &["empty.bin", "plain.txt"];

/// Find the strongest candidate from a probe result.
fn strongest(
    candidates: &[diec_core::format::FormatCandidate],
) -> Option<&diec_core::format::FormatCandidate> {
    candidates
        .iter()
        .rev()
        .find(|c| c.strength == FormatStrength::Strong)
        .or_else(|| {
            candidates
                .iter()
                .rev()
                .find(|c| c.strength == FormatStrength::Weak)
        })
}

/// Resolve the corpus directory relative to the workspace root.
fn corpus_dir() -> PathBuf {
    // CARGO_MANIFEST_DIR is crates/diec-formats; workspace root is two levels up.
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    PathBuf::from(manifest_dir)
        .parent() // crates/
        .and_then(|p| p.parent()) // workspace root
        .map(|p| p.join("corpus"))
        .unwrap_or_else(|| PathBuf::from("corpus"))
}

/// Read a corpus file, returning its bytes or skipping the test.
fn read_corpus(name: &str) -> Vec<u8> {
    let path = corpus_dir().join(name);
    if !path.exists() {
        eprintln!(
            "SKIP: corpus file missing: {name} (looked in {})",
            path.display()
        );
        return Vec::new();
    }
    std::fs::read(&path).unwrap_or_else(|e| panic!("cannot read corpus file {name}: {e}"))
}

/// Run the probe table on raw bytes and return (candidates, errors).
fn probe_bytes(
    data: &[u8],
) -> (
    Vec<diec_core::format::FormatCandidate>,
    Vec<diec_formats::ProbeError>,
) {
    let src = MemorySource::new(data);
    let range = ByteRange::new(0, src.len()).unwrap();
    let view = ByteView::new(&src, range).unwrap();
    let table = ProbeTable::default_phase2();
    table.probe_all(&view)
}

#[test]
fn corpus_format_detection_matches_expected() {
    let mut tested = 0usize;
    let mut skipped = 0usize;
    let mut mismatches = Vec::new();

    for (name, expected) in CORPUS_EXPECTATIONS {
        let data = read_corpus(name);
        if data.is_empty() {
            skipped += 1;
            continue;
        }

        let (candidates, errors) = probe_bytes(&data);

        if !errors.is_empty() {
            mismatches.push(format!("{name}: unexpected probe errors: {errors:?}"));
            continue;
        }

        let detected = strongest(&candidates)
            .map(|c| c.file_type.name.as_str())
            .unwrap_or("(none)");

        if detected != *expected {
            mismatches.push(format!("{name}: expected '{expected}', got '{detected}'"));
        }
        tested += 1;
    }

    assert!(tested > 0, "no corpus samples were tested");
    assert!(
        mismatches.is_empty(),
        "format detection mismatches ({}):\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
    eprintln!("corpus differential: {tested} tested, {skipped} skipped, 0 mismatches");
}

#[test]
fn corpus_non_binary_produces_no_candidates() {
    for name in CORPUS_NO_MATCH {
        let data = read_corpus(name);
        if data.is_empty() {
            continue;
        }
        let (cands, errs) = probe_bytes(&data);
        assert!(
            cands.is_empty(),
            "{name}: expected no candidates, got {cands:?}"
        );
        assert!(errs.is_empty(), "{name}: expected no errors, got {errs:?}");
    }
}

#[test]
fn corpus_pe32_also_produces_msdos_weak() {
    let data = read_corpus("minimal.exe");
    if data.is_empty() {
        return;
    }
    let (cands, errs) = probe_bytes(&data);
    assert!(errs.is_empty());
    // PE files start with MZ, so MSDOS weak should also appear.
    let has_msdos = cands.iter().any(|c| c.file_type.name == "MSDOS");
    let has_pe32 = cands.iter().any(|c| c.file_type.name == "PE32");
    assert!(
        has_msdos,
        "PE32 file should also produce MSDOS weak candidate"
    );
    assert!(has_pe32, "PE32 file should produce PE32 strong candidate");
}

#[test]
fn corpus_pe64_also_produces_msdos_weak() {
    let data = read_corpus("minimal-pe64.exe");
    if data.is_empty() {
        return;
    }
    let (cands, errs) = probe_bytes(&data);
    assert!(errs.is_empty());
    let has_msdos = cands.iter().any(|c| c.file_type.name == "MSDOS");
    let has_pe64 = cands.iter().any(|c| c.file_type.name == "PE64");
    assert!(
        has_msdos,
        "PE64 file should also produce MSDOS weak candidate"
    );
    assert!(has_pe64, "PE64 file should produce PE64 strong candidate");
}

#[test]
fn corpus_zip_based_formats_detect_zip() {
    // APK, JAR, IPA are all ZIP-based; the probe should detect ZIP.
    for name in &["payload.zip", "minimal.apk", "minimal.jar", "minimal.ipa"] {
        let data = read_corpus(name);
        if data.is_empty() {
            continue;
        }
        let (cands, errs) = probe_bytes(&data);
        assert!(errs.is_empty(), "{name}: unexpected errors: {errs:?}");
        let has_zip = cands.iter().any(|c| c.file_type.name == "ZIP");
        assert!(has_zip, "{name}: should detect ZIP, got {cands:?}");
    }
}
